### ISSUE TITLE
Different between WakefulBroadcastReceiver and WakefulIntentService

### ISSUE THREAD

**Issue by nguyencongbinh** [commonsguy/cwac-wakeful#27]
Hello CommonsWare,

Firstly, thank you so much for this library. Can you tell me the different between using WakefulBroadcastReceiver and your library.  I am using WakefulBroadcastReceiver  but sometime (just sometime), the alarm not fire. This issue happen on so many devices. I do not know why.  Does this library fix this issue ? 
Thank you and hop you reply to me.

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. Please use [the support options from the project `README`](https://github.com/commonsguy/cwac-wakeful#questions).

> Does this library fix this issue ?

Probably not. As of Android 6.0, `AlarmManager`, `JobScheduler`, and similar mechanisms become erratic, due to Doze mode and app standby.
