### ISSUE TITLE
Question: about JobIntentService alternative on Android O...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [commonsguy/cwac-wakeful#29]
According to the docs, it's not promised to be launched right away.
What if I want to start a service that will surely use the Internet (foreground service and/or with wakelocks if needed), and run right away?

Did Android O really stop supporting such a thing?

I ask this because of this issue (need to use Internet connection on battery saver mode after phone event) :
https://stackoverflow.com/q/45976482/878126

**Comment by commonsguy** [comment]
> What if I want to start a service that will surely use the Internet (foreground service and/or with wakelocks if needed), and run right away?

Very few scenarios exist in which that degree of timing is required, because the trigger for that service itself will be inexact. Take `AlarmManager` for example. Given Doze mode, you have no idea when your alarms will actually go off. Hence, worrying about an additional delay due to the vagaries of `JobScheduler` with respect to `JobIntentService` is pointless.

Yours in part happens to be one scenario where timing may be important. I say "in part" because only your `NEW_OUTGOING_CALL` receiver might work, `PHONE_STATE` doesn't seem to be on the implicit broadcast whitelist, so you can't register for that in the manifest on Android 8.0 AFAIK.

> Did Android O really stop supporting such a thing?

They made it more difficult. `WakefulIntentService` would need some retrofitting to use `startForegroundService()` (at least as an option) instead of `startService()`.

**Comment by AndroidDeveloperLB** [comment]
Actually, if you want an alarm to be triggered on some point, it's very crucial it will be on this time.
Imagine you need to wake up for work, but it will decide that it's not important to be on the time you've set it to be... Or maybe you mean in other scenarios?
But anyway, I wrote about battery-saver too. Why wouldn't the Internet be available on this case, and yet if I wait a very short time (usually less than 100ms in my case), it's available? How could it be? 

About the BroadcastReceiver, it seems to work fine on Android O, even if I target Android O.

Do you know perhaps of a way to overcome the situation I've found?
That upon phone call, when the device has battery-saver turned on, there is no Internet connection (yet it might come back very soon after for some reason) ?
If so, please check the StackOverflow question and offer your answer there. 

Currently, the only workaround I've found, is to poll the Internet connection availability (I know, a stupid solution, but only thing that worked so far) for the first second (every 10ms for example), and if there isn't Internet yet, we will probably never get it later anyway.
I tried to use WakefulIntentService. I tried to use WakeLock. I tried to use a receiver for connection availablility. And, of course I tried to use foreground service.
Maybe one of my implementations was wrong too. I might have made some mistakes on the way...

I hope you can answer this. If you really have a solution, I will be glad to grant the bounty :)

**Comment by commonsguy** [comment]
> That upon phone call, when the device has battery-saver turned on, there is no Internet connection (yet it might come back very soon after for some reason) ?

I have never researched anything vaguely resembling this scenario, sorry.

**Comment by AndroidDeveloperLB** [comment]
I have the sample project for this, here:
https://issuetracker.google.com/issues/65395920#comment1
And with the only workaround that I've found, here:
https://issuetracker.google.com/issues/65395920#comment6
